#ifndef EXPERIMENTAL_FORTRAN_FOR_WINDOWS_FORTRAN_INCLUDE_FLIB_H
#define EXPERIMENTAL_FORTRAN_FOR_WINDOWS_FORTRAN_INCLUDE_FLIB_H

extern "C" {
void test_(int*, int*, int*, const double* t);
}

#define test test_

#endif  // EXPERIMENTAL_FORTRAN_FOR_WINDOWS_FORTRAN_INCLUDE_FLIB_H
