#ifndef EXPERIMENTAL_FORTRAN_FOR_WINDOWS_FORTRAN_INCLUDE_FLIB_H
#define EXPERIMENTAL_FORTRAN_FOR_WINDOWS_FORTRAN_INCLUDE_FLIB_H

extern "C" {
void addone_(const double* t);
}

#define addone addone_

#endif  // EXPERIMENTAL_FORTRAN_FOR_WINDOWS_FORTRAN_INCLUDE_FLIB_H
