name: Build Fortran and then C++

on:
  push:
  schedule:
    - cron: '0 2 * * SAT'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "Linux Debug"
            os: ubuntu-20.04
            mode: Debug
          - name: "macOS Debug"
            os: macOS-10.15
            mode: Debug
          - name: "Windows Debug"
            os: windows-2019
            mode: Debug

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2'

      - name: Define local variables
        shell: bash
        run: |
          echo "MODE=${{matrix.mode}}" >> $GITHUB_ENV
          
      - name: script
        shell: bash
        run: |
          pushd fortran
          mkdir build && cd build
          cmake \
            -DCMAKE_Fortran_COMPILER=$(command -v gfortran) \
            -G "Unix Makefiles" \
            -DCMAKE_BUILD_TYPE="${MODE}" ..
          cmake --build . --target install --config "${MODE}"
          popd
          pushd cpp
          mkdir build && cd build
          cmake -DCMAKE_BUILD_TYPE="${MODE}" ..
          cmake --build .
          
          

